{
  "hash": "bb8454e0b86349460b04feaf690c7f96",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Topic 5 -- Introduction to hypothesis testing\nauthor: Floris van Ogtrop\nformat:\n  ochre-revealjs: default\n  ochre-typst: default\n---\n\n## Important Notice\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nThe Faculty has been informed of instances where students are being targeted by illegitimate academic services, which could potentially lead to plagiarism or other breaches.\n\nThis can include:\n\n- “tutoring” services who provide assignment instructions or model answers;\n- using another person or company to write or complete your assignment;\n- using online file-sharing sites that lead to plagiarism.\n\nEngaging in such activities could constitute a breach of the Academic Integrity Policy  and may result in penalties, including failing the assignment, the unit, or even a suspension or exclusion for misconduct.\n\n:::\n\n::: {.column width=\"50%\"}\n\nWe want you to do well on assessments. Contact the Learning Hub, you tutor, or Unit Coordinator to get support.\n\nThere are resources available to help you. Don’t be afraid to ask for help.\n\n![](images/QR1.png)\n\n:::\n\n::::\n\n# Outline\n\n- Why do inferential statistics?\n- Hypothesis testing;\n- One-sample tests;\n- Confidence intervals;\n- Transformations.\n\n## Learning outcomes\n\n::: {style=\"background-color: yellow; padding: 10px; border: 1px solid black;\"}\n**LO1**. By the end of this course, students will be able to implement basic reproducible research practices—including consistent data organization, documented code, and version-controlled workflows—so that their statistical analyses and results can be readily replicated and validated by others.\n:::\n\n::: {style=\"background-color: yellow; padding: 10px; border: 1px solid black;\"}\n**LO2**. By the end of this course, students will demonstrate proficiency in utilizing R and Excel to effectively explore and describe life science datasets.\n:::\n\n::: {style=\"background-color: yellow; padding: 10px; border: 1px solid black;\"}\n**LO3**. By the end of this course, students will be able to apply parametric and non-parametric statistical inference methods to experimental and observational data using RStudio and effectively interpret and communicate the results in the context of the data.\n:::\n\nLO4. By the end ot this course, students will be able to put into practice both linear and non-linear models to describe relationships between variables using RStudio and Excel, demonstrating creativity in developing models that effectively represent complex data patterns.\n\n::: {style=\"background-color: yellow; padding: 10px; border: 1px solid black;\"}\n**LO5**. By the end of this course, students will be able to articulate statistical and modelling results clearly and convincingly in both written reports and oral presentations, working effectively as an individual and collaboratively in a team, showcasing the ability to convey complex information to varied audiences.\n:::\n\n\n## Inferential statistics\n\n- So far we have focused on Exploratory Data Analysis **EDA**;\n- **EDA** helps us describe and visualise data;\n- **Inferential statistics** takes the next step: using a **sample** to learn about a **population**;\n- This is an important and sometimes difficult step in statistics;\n- Because samples vary by chance, we need formal methods to decide whether an observed difference is likely to reflect the real effect.\n\n\n\n## Hypothesis testing\n\n- In statistics, a **hypothesis** is a claim about a population parameter.\n- We often begin with a **benchmark** or **reference value**\n- We then ask:\n\n> Is our sample consistent with that claim, or is the difference too large to plausibly due to chance alone?\n\n\n## Hypothesis testing\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n- Suppose the guideline value for Total Nitrogen (TN) at a site along a river is $500 \\mu g/L$\n- We might ask\n\n> Is the mean TN concentration at this site equal to $500 \\mu g/L$, or is it different?\n\n- This gives us a natural hypothesis test:\n  - **Null hypothesis** $H_0:$ the mean TN concentration is $500 \\mu g/L$\n  - **Alternative hypothesis** $H_1:$ the mean TN concentration is **NOT** $500 \\mu g/L$\n\n:::\n\n::: {.column width=\"50%\"}\n\n![Grose River - Floris van Ogtrop](images/stream1.png)\n\n:::\n\n::::\n\n\n## Hypothesis testing workflow\n\n**We will follow the steps in hypothesis testing**\n\n1. State the hypotheses;\n2. Check assumptions;\n3. Calculate the test statistic;\n4. Obtain P-value, critical value, confidence intervals;\n5. Draw the statistical conclusion;\n6. Write a scientific (biological) conclusion.\n\n\n## Hypothesis testing workflow\n\nA usefull acronym is **HATPC**:\n\n- **H:** Hypothesis\n- **A:** Assumptions\n- **T:** Test statistic\n- **P:** P-Value\n- **C:** Conclusion\n\n\n## H: Hypothesis\n\n- The **null hypothesis** $(H_0)$ is the benchmark or reference claim\n- The **alternative hypothesis** $(H_1)$ is the competing claim we are interested in.\n\nFor example\n\n- $H_0:\\mu = 500 \\mu g/L$\n- $H_1:\\mu \\ne 500 \\mu g/L$\n\n\n## A: Assumptions\n\n- Before carrying out a t-test, we need to check whether its assumptions are reasonable;\n- For a one sample t-test, an important assumption is that the sample data is approximately normally distributed.\n- We usually check this by:\n\n1. looking at the data using plots\n2. Checking for strong skewness or outliers\n3. Optionally using a formal test such as the Shapiro-Wilk test\n\n## T: Test Statistic \n\nA test statistic measure show far the observed result is from what we would expect under the null hypothesis.\n\n$\\text{Test statistic}=\\frac{\\text{Observed value - Expected value}}{\\text{Standard error}}$\n\nThis is essentially\n\n$=\\frac{\\text{Signal}}{\\text{Noise}}$\n\n- **Numerator** = difference from the null value\n- **Denominator** = uncertainty in that estimate\n\n\n## P: p-value\n\n- The **p-value** tells us how unusual our results would be **if the null hypothesis were true**\n\nMore formally:\n\n- It is the probability of observing the test statistic, or something more extreme, assuming $H_0$ is true.\n\nSo the p-value helps us judge whether the data are **consistent with** the null hypothesis.\n\n\n\n\n## P: p-value\n\n**What does this have to do with sampling distributions??**\n\n![](images/two_tail.png)\n\n\n\n\n## P: p-value\n\nA useful memory aid is:\n\n**\"If the P-value is low the Null hypothesis must go.\"** \n\nBut more formally:\n\n- If $p < 0.05$ the data provide evidence against $H_0$\n- If $p \\ge 0.05$ the data do not provide strong evidence against $H_0$\n\nImportant:\n\n- We **do not accept** $H_0$\n- We say **we fail to reject** $H_0$\n\n\n## P: p-value\n\n**Common mistakes**\n\n- The p-value is not the chance that the NULL hypothesis is true\n- A large p-value does not mean that $H_0$ is true\n\n![](images/p_value.png)\n\n- The use of 0.05 is not mandatory, it is a convention.\n- Other levels such as 0.01 or 0.001 may also be used.\n\n\n## P: p-value\n\n**Controversy**\n\n[Nature article 1](https://www.nature.com/news/statisticians-issue-warning-over-misuse-of-p-values-1.19503) \n\n[Nature article 2](https://www.nature.com/articles/d41586-019-00857-9) \n\n- Should we move away from an over reliance on p-values towards more robust statistical methods and a greater emphasis on the size and reproducibility of effects?\n- Look up terms like **\"P Hacking\"**...\n\n\n## C: Conclusion\n\nAt the end of a statistical test we write two conclusions\n\n1. A **statistical conclusion** based on the test statistic, confidence intervals, p-value and the level of significance i.e. we reject or fail to reject $H_0$\n2. A **scientific (biological) conclusion** what does this mean in the context of the study.\n\n\n## One or Two - Tails\n\n![](images/tails.png)\n\n\n## One or Two - Tails\n\n- Suppose we want to compare a sample population or sample mean $(\\mu)$ to a benchmark value $(c)$ - Could be our water quality benchmark of $c=500 \\mu g/L$\n\n  - $H_0:\\mu=c$ *Two tailed*\n  - $H_1:\\mu \\ne c$ *Two tailed*\n  \n  - $H_0:\\mu \\ge c$ *One tailed - greater than*\n  - $H_1:\\mu < c$ *One tailed - greater than*\n  \n  - $H_0:\\mu \\le c$ *One tailed - less than*\n  - $H_1:\\mu > c$ *One tailed - less than*\n  \n- We usually use the first (two tailed) form unless we are specifically interested in testing whether the difference is in one direction because this is the only direction of interest\n\n\n## One-tailed tests (water quality)\n\n| Goal | Hypotheses | Tail |\n|------|-----------|------|\n| Detect unsafe water | H₀: μ ≤ c, H₁: μ > c | Right |\n| Demonstrate safe water | H₀: μ ≥ c, H₁: μ < c | Left |\n\n> **Rule:** The tail follows the alternative hypothesis (H₁)\n\n\n\n## Type one or type two error\n\n**Type I error**\n\n- False positive: we reject H0  when it is true \n\n**Type II error**\n\n- False negative: we accept H0  when it is false\n\n![](images/error.png)\n\n**Note:** Decreasing the significance level ($\\alpha$) to say 0.01 will increase the probability of type II error\n\n\n\n## Sample size and power\n\n**Power** is the probability a test will detect a real effect when one exists.\n\n- **High power** means a low chance of type II error;\n- **Low power** means a higher chance of missing a real effect.\n\nIn general:\n\n- larger sample sizes increase power;\n- smaller standard deviations increase power;\n- larger effects are easier to detect.\n\n\n## The t-distribution\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nThe t-distribution is:\n\n-\tbell-shaped;\n- symmetric;\n- centred on zero;\n- similar in shape to the normal distribution, but with **heavier tails**.\n\nIts exact shape depends on the **degrees of freedom**\n\n- For a one-sample t-test $df=n-1$ where n is the sample size.\n- As the sample size increases, the t-distribution becomes more similar to the normal distribution.\n\n:::\n\n::: {.column width=\"50%\"}\n\n![Comparing the shapes of the Student’s T and the Z (normal) curve](images/tdist.png)\n\n:::\n\n::::\n\n\n## Class exercise: One sample t-test\n\nSuppose we wish to test whether the mean resting heart rate of ENVX1002 students differs from a benchmark value of 70 beats per minute (bpm). \n\nWe are going to do this exercise in class but I have provided a simulated example below so you have it in the slides as well.\n\n## Class exercise: One sample t-test\n\nWe will simulate some data for 30 students in our ENVX1002 class. To do this we will draw 30 random numbers from a normal distribution with a mean of 70 and a standard deviation of 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1974)\nheart_rate <- rnorm(30, mean = 70, sd = 10)\n```\n:::\n\n\n## Class exercise: <span style=\"color: blue;\">**H**</span>ypothesis\n\n**State the Null and Alternate hypothesis!**\n\n- $H_0=70 \\text{ bpm}$\t(Null hypothesis)\n\n- $H_1 \\ne 70 \\text{ bpm}$\t(Alternate hypothesis)\n\n\n## Class example: <span style=\"color: blue;\">**A**</span>ssumptions\n\nBefore applying a one-sample t-test, we should check whether the sample is approximately normally distributed. Consider the following:\n\n| Sample size | Histogram | Q-Q plot | Jitter plot | Boxplot | Shapiro test |\n|-------------|-----------|----------|-------------|---------|--------------|\n| **Small** (*n* < 30) | Limited | **Best** | **Very useful** | **Useful** | Cautious use |\n| **Medium** (30–100) | Useful | **Very useful** | Useful | Useful | Sometimes useful |\n| **Large** (*n* > 100) | Useful | **Best** | Less useful | **Good (outliers)** | Too sensitive |\n\n> **Rule of thumb:**  \n> - Small *n*: **show the data** (jitter) + Q-Q plot  \n> - Larger *n*: **histogram + Q-Q plot**  \n> - Use boxplots to highlight **spread and outliers**, not normality alone\n\n## Class example: <span style=\"color: blue;\">**A**</span>ssumptions\n\nWe begin by looking at the data (EDA). Ours sample size is 30 so we can look at the histogram, Q-Q plot and jitter plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(patchwork)\n\ndf <- data.frame(heart_rate)\n\np1 <- ggplot(df, aes(heart_rate)) +\n  geom_histogram(fill = \"grey80\", colour = \"white\", bins = 30) +\n  labs(title = \"Histogram\", x = \"Heart rate\", y = \"Count\") +\n  theme_minimal()\n\np2 <- ggplot(df, aes(sample = heart_rate)) +\n  stat_qq() +\n  stat_qq_line(colour = \"red\") +\n  labs(title = \"Q-Q plot\", x = \"Theoretical\", y = \"Sample\") +\n  theme_minimal()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](lecture-05_files/figure-revealjs/unnamed-chunk-2-1.png){width=768}\n:::\n:::\n\n\n\n## Class example: <span style=\"color: blue;\">**A**</span>ssumptions\n\nAs an option, we can also use the Shapiro-Wilk test as a supporting check. Best if the sample size is less than 50.\n\n- If \\(p > 0.05\\), we do not have strong evidence against normality;\n- This does not prove normality, but suggests the t-test may be reasonable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(heart_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  heart_rate\nW = 0.95114, p-value = 0.1814\n```\n\n\n:::\n:::\n\n\n\n## Class example: <span style=\"color: blue;\">**T**</span>est\n\nFor a one-sample t-test, the test statistic is:\n\n$t = \\frac{\\bar{y} - \\mu}{s/\\sqrt{n}}$\n\nwhere:\n\n- $\\bar{y}$ = sample mean\n- $\\mu$ = null (benchmark) value\n- $s$ = sample standard deviation\n- $n$ = sample size\n\n\n## Class example: <span style=\"color: blue;\">**T**</span>est\n\n<span style=\"color: blue;\">**CI**</span> &\n<span style=\"color: blue;\">**T**</span>-Statistic & \n<span style=\"color: blue;\">**P**</span>-value\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\nIn R, the one-sample t-test gives us:\n\n- the test statistic\n- degrees of freedom\n- the p-value\n- the confidence interval\n- the sample mean\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(heart_rate,\n  mu = 70,\n  alternative = \"two.sided\",\n  conf.level = 0.95\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  heart_rate\nt = 0.25373, df = 29, p-value = 0.8015\nalternative hypothesis: true mean is not equal to 70\n95 percent confidence interval:\n 66.76984 74.14513\nsample estimates:\nmean of x \n 70.45748 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nWe can see the following output:\n\n- the t-statistic = 0.25373\n- the degrees of freedom = 29 $(n-1)$\n- the p-value = 0.8015\n- the 95% confidence interval = (66.76984 74.14513)\n- the sample mean = 70.45748\n\n:::\n\n::::\n\n## Class example: <span style=\"color: blue;\">**C**</span>onclusion\n\n### Statistical conclusion\nBecause \\(p = 0.8015 > 0.05\\), we **fail to reject the null hypothesis**.\n\n### Scientific conclusion\nThe data do not provide strong evidence that the mean resting heart rate of ENVX1002 students differs from 70 bpm.\n\nAlso note:\n- 70 bpm lies within the 95% confidence interval\n- this is consistent with the non-significant test result \n\n\n\n## Confidence intervals\n\nA **confidence interval** gives a range of plausible values for an unknown population parameter.\n\nMany people prefer confidence intervals because they show:\n\n- the estimated value\n- the uncertainty around that estimate\n\nA hypothesis test gives a decision about a claim.\nA confidence interval gives a plausible range.\n\n\n\n## Confidence intervals - known variance\n\n- Assuming our sample comes from a normal population, we can calculate the confidence interval for the mean of a population when the population **variance is known**. An example may be in manufacturing where we know the variance of a process.\n- The formula for the confidence interval is:\n\n$CI = \\bar{y} \\pm Z_{\\alpha/2} \\cdot \\frac{\\sigma}{\\sqrt{n}}$\n\nfor the 95% confidence interval, $\\alpha = 0.05$ and $Z_{\\alpha/2} = 1.96$ i.e. 2 standard errors from the mean.\n\n\n\n## Confidence intervals - Unknown variance\n\nIn practice, we usually do **not** know the population variance.\n\nIn that case, we use the t-distribution:\n\n$CI = \\bar{y} \\pm t_{\\alpha/2,df}\\frac{s}{\\sqrt{n}}$\n\nwhere:\n\n- $s$ is the sample standard deviation\n- $df = n - 1$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(0.975, df = 29) ## in our heart rate example, n=30 so df = 29 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.04523\n```\n\n\n:::\n:::\n\n\n\n\n## Confidence intervals - Unknown variance\n\n- The following is simulation of 100 studies, each containing n = 6 observations of a fictitious toxic substance concentration ($\\mu g / l$) assumed to be $\\sim N(0.3, 0.12)$. \n- For each sample the 95% confidence interval calculated: \n\n![Depiction of confidence intervals from each of 100 simulated samples](images/CI_sim.png)\n\n## Confidence intervals - Unknown variance\n\n- In the graph on the previous slide, a confidence interval includes the true mean value of 0.3 if the vertical line (representing the width of the CI) crosses the horizontal line.\n- We have to accept that 5% of the time we will not capture the true mean.\n- We can widen the confidence interval to 99% so we are more confident but this can increase the chance of a type II error. \n\n\n## Example 2: Water Quality \n\nLet's look at our water quality example again:\n\n- The data is Total Nitrogen (TN) levels @ Wallacia in western Sydney on the Nepean River\n- According to the ANZECC guidelines, the maximum acceptable level of TN in an lowland river is 500 $\\mu g/L$ and for an upland river = 250 $\\mu g/l$. (see Table 3.3.2 in Australian and New Zealand Guidelines for Fresh and Marine Water Quality)\n- We want to know if the observed mean value of TN in our sample is different to the guideline value of 500 $\\mu g/L$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTN <- read.csv(\"data/TN_Wallacia.csv\")\nstr(TN)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t29 obs. of  1 variable:\n $ TN: int  1020 1120 1170 920 920 1010 850 910 800 710 ...\n```\n\n\n:::\n:::\n\n  \n\n## Example 2: Water Quality\n\n**State Hypothesis**\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n- $H_0: \\mu = 500$ $\\mu g/l$ (Null hypothesis)\n- $H_1: \\mu \\ne 500$ $\\mu g/l$ (Alternate hypothesis)\n\n:::\n\n::: {.column width=\"50%\"}\n\n![Grose River - Floris van Ogtrop](images/stream1.png)\n\n:::\n\n::::\n\n\n\n## Example 2: Water Quality\n\n**Check assumptions**\n\nWhat do we notice about the plots? Does the data look normally distributed? Do we see strong skewness or outliers?\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(gridExtra)\n\n# Histogram\np1 <- ggplot(TN, aes(x = TN)) +\n  geom_histogram(\n    fill = \"blue\", color = \"black\",\n    bins = 7\n  ) +\n  xlab(\"Total Nitrogen (ug/L)\") +\n  theme_minimal()\n\n# Boxplot\np2 <- ggplot(TN, aes(x = TN)) +\n  geom_boxplot(fill = \"blue\") +\n  xlab(\"Total Nitrogen (ug/L)\") +\n  theme_minimal()\n\n# Q-Q plot\np3 <- ggplot(TN, aes(sample = TN)) +\n  stat_qq() +\n  stat_qq_line(col = \"red\") +\n  theme_minimal()\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Arrange the plots in a 2x2 layout\ngrid.arrange(p1, p2, p3, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](lecture-05_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n:::\n::::\n\n\n## Example 2: Check assumptions\n\n**Shapiro-Wilk normality test**\n\n- For smaller sample sizes, we can use the Shapiro-Wilk test (say < 50) to confirm whether the data is normally distributed or not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(TN$TN)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  TN$TN\nW = 0.92582, p-value = 0.04293\n```\n\n\n:::\n:::\n\n\n- We see P<0.05 so we **reject** the null hypothesis that the data is normally distributed.\n- For really large samples (>>30) the central limit theorem suggests that the distribution of the sample means tends to be normal. However, extreme skewness, heavy tails, or outliers can still affect the test's performance.\n\n\n\n## Example 2: Transformations\n\nFor right (positive) skewed data, we can use a \n\n- $1/x$ inverse transformation for highly skewed data.\n- $\\log_{10}$ or $\\log_e$ transformation for very skewed data. \n- $\\sqrt{x}$ square root transformation for moderately skewed data.\n  \nFor left (negative) skewed data (which is rare to find), we can \"try\" a\n\n- $x^2$, $x^3$ or $e^x$ transformation.\n\n\n\n## Example 2: Transformations & Recheck assumptions\n\nLet's try a log10 transformation:\n\n- We start by creating a new column in our data frame called log10_TN\n- We then take the log10 of the TN column and store it in the new column - note we could also use \"mutate\" from the dplyr package to do this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTN$log10_TN <- log10(TN$TN)\n```\n:::\n\n\n## Example 2: Recheck assumptions\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(gridExtra)\n\n# Histogram\np1 <- ggplot(TN, aes(x = log10_TN)) +\n  geom_histogram(\n    fill = \"blue\", color = \"black\",\n    bins = 7\n  ) +\n  xlab(\"Log10 Total Nitrogen (ug/L)\") +\n  theme_minimal()\n\n# Boxplot\np2 <- ggplot(TN, aes(x = log10_TN)) +\n  geom_boxplot(fill = \"blue\") +\n  xlab(\"log10 Total Nitrogen (ug/L)\") +\n  theme_minimal()\n\n# Q-Q plot\np3 <- ggplot(TN, aes(sample = log10_TN)) +\n  stat_qq() +\n  stat_qq_line(col = \"red\") +\n  theme_minimal()\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Arrange the plots in a 2x2 layout\ngrid.arrange(p1, p2, p3, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](lecture-05_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n:::\n::::\n\n\n## Example 2: Recheck assumptions\n\n**Shapiro-Wilk normality test**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(TN$log10_TN)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  TN$log10_TN\nW = 0.97279, p-value = 0.6375\n```\n\n\n:::\n:::\n\n\n- From our previous slide, our data seems to be quite symmetrical\n- Now P>0.05 so we **fail to reject** the null hypothesis that the data is normally distributed.\n- We can now proceed with our t-test using the log transformed data.\n\n## Example 2: Restate the hypotheses\n\n- We will also need to transform the hypothesised mean of 500 to the log10 scale.\n\n- $H_0: \\mu = log10(500)$ $\\mu g/l$ (Null hypothesis)\n- $H_1: \\mu \\ne log10(500)$ $\\mu g/l$ (Alternate hypothesis)\n\n\n\n## Example 2: T-test & P-Value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(TN$log10_TN,\n  mu = log10(500),\n  alternative = \"two.sided\",\n  conf.level = 0.95\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  TN$log10_TN\nt = 4.8768, df = 28, p-value = 3.884e-05\nalternative hypothesis: true mean is not equal to 2.69897\n95 percent confidence interval:\n 2.807748 2.965309\nsample estimates:\nmean of x \n 2.886528 \n```\n\n\n:::\n:::\n\n\n- The p-value is <0.001 (3.d.p.) which is less than 0.05. Therefore, we reject the null hypothesis. \n- There is strong evidence that the mean value of TN in Nepean River is different to 500 ug/L. \n- Can we say something about the direction??\n\n\n## Example 2: Geometric mean & Confidence intervals\n\n**Geometric mean**\n\nNote that now we are looking at the geometric mean as opposed the the arithmatic mean which was 855.86 in our case\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10^mean(TN$log10_TN)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 770.0666\n```\n\n\n:::\n:::\n\n\n**Confidence intervals**\n\n- We need to back transform the confidence interval to the original scale.\n- To back-transform the confidence interval we can use the following:\n\n$10^{CI_{low}}$ and $10^{CI_{high}}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10^(2.81)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 645.6542\n```\n\n\n:::\n\n```{.r .cell-code}\n10^(2.97)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 933.2543\n```\n\n\n:::\n:::\n\n\n- This means that we are 95% confident that the geometric mean (back-transformed mean) of the sample is between approximately 646 and 933 ug/l. This is higher than the hypothesised mean.\n\n\n\n## Example 2: Conclusion\n\n1. The data was log10 transformed to meet the assumptions of the t-test.\n2. We have strong evidence that the mean value of Total Nitrogen in Nepean River is different to 500 ug/L.\n3. We are 95% confident that the geometric mean (back-transformed mean) of the sample is between approximately 646 and 933 ug/l.\n4. Looking at the confidence interval, we can say that the mean value of TN in Nepean River is significantly greater than 500 ug/L.\n\n\n\n\n\n## Example 3: One tailed test\n\n- We can also use a one tailed test if we are specifically interested in whether the observed value is greater or less than the expected value.\n- In this case we only want to know if the TN concentration is greater than the ANZECC guidelines of 500 $\\mu g/l$.\n\n> Detect unsafe water | H₀: μ ≤ 500, H₁: μ > 500 |\n\nOR\n\n> Detect unsafe water | H₀: μ ≤ $log_{10}500$, H₁: μ > $log_{10}500)$ |\n\n\n## Example 3: One tailed test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(TN$log10_TN,\n  mu = log10(500),\n  alternative = \"greater\",\n  conf.level = 0.95\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  TN$log10_TN\nt = 4.8768, df = 28, p-value = 1.942e-05\nalternative hypothesis: true mean is greater than 2.69897\n95 percent confidence interval:\n 2.821104      Inf\nsample estimates:\nmean of x \n 2.886528 \n```\n\n\n:::\n:::\n\n\n- P < 0.001 (3.d.p.) so we reject the null hypothesis.\n- Because we are doing a one tailed test we can now conclude that the mean value of TN in Nepean River is greater than $log_{10}500 \\mu g/L$\n- Take a look at the confidence interval and the p-value. What do you notice when comparing to the two tailed test?\n\n\n\n## Example 3: One tailed test\n\n[Ruxton and Neuhäuser 2010](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2010.00014.x)\n\n![](images/one_tail.png)\n\n\n\n\n# References\n\n- Quinn G. P. & Keough M. J. (2002) Experimental design and data analysis for biologists. Cambridge University Press, Cambridge, UK.\n- Logan, M. (2010). Biostatistical design and analysis using R a practical guide. Hoboken, N.J., Wiley-Blackwell.\n- Fox, G. A., S. Negrete-Yankelevich, and V. J. Sosa. (2015). Ecological statistics: contemporary theory and application. Oxford University Press, USA\n- Ruxton, G.D. and Neuhäuser, M., 2010. When should we use one-tailed hypothesis testing? Methods in Ecology and Evolution, 1 (2), 114-117.\n\n\n\n# Thanks!\n\nThis presentation is based on the [SOLES Quarto reveal.js template](https://github.com/usyd-soles-edu/soles-revealjs) and is licensed under a [Creative Commons Attribution 4.0 International License][cc-by].\n\n\n<!-- Links -->\n[cc-by]: http://creativecommons.org/licenses/by/4.0/",
    "supporting": [
      "lecture-05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}