<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Floris van Ogtrop">
  <title>Topic 5 – Introduction to hypothesis testing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-db369ac6a2a3b7745e1b1c2a74c34a6d.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="../../site_libs/quarto-contrib/quarto-project/ochre/logo_charcoal.svg" data-background-position="bottom 4em center" data-background-size="10%" class="quarto-title-block center">
  <h1 class="title">Topic 5 – Introduction to hypothesis testing</h1>
  <p class="subtitle">ENVX1002 Statistics in Life and Environmental Sciences</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Floris van Ogtrop 
</div>
        <p class="quarto-title-affiliation">
            The University of Sydney
          </p>
    </div>
</div>

  <p class="date">Mar 2026</p>
</section>
<section id="important-notice" class="slide level2">
<h2>Important Notice</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>The Faculty has been informed of instances where students are being targeted by illegitimate academic services, which could potentially lead to plagiarism or other breaches.</p>
<p>This can include:</p>
<ul>
<li>“tutoring” services who provide assignment instructions or model answers;</li>
<li>using another person or company to write or complete your assignment;</li>
<li>using online file-sharing sites that lead to plagiarism.</li>
</ul>
<p>Engaging in such activities could constitute a breach of the Academic Integrity Policy and may result in penalties, including failing the assignment, the unit, or even a suspension or exclusion for misconduct.</p>
</div><div class="column" style="width:50%;">
<p>We want you to do well on assessments. Contact the Learning Hub, you tutor, or Unit Coordinator to get support.</p>
<p>There are resources available to help you. Don’t be afraid to ask for help.</p>
<p><img data-src="images/QR1.png"></p>
</div></div>
</section>
<section>
<section id="outline" class="title-slide slide level1 center">
<h1>Outline</h1>
<ul>
<li>Why do inferential statistics?</li>
<li>Hypothesis testing;</li>
<li>One-sample tests;</li>
<li>Confidence intervals;</li>
<li>Transformations.</li>
</ul>
</section>
<section id="learning-outcomes" class="slide level2">
<h2>Learning outcomes</h2>
<div style="background-color: yellow; padding: 10px; border: 1px solid black;">
<p><strong>LO1</strong>. By the end of this course, students will be able to implement basic reproducible research practices—including consistent data organization, documented code, and version-controlled workflows—so that their statistical analyses and results can be readily replicated and validated by others.</p>
</div>
<div style="background-color: yellow; padding: 10px; border: 1px solid black;">
<p><strong>LO2</strong>. By the end of this course, students will demonstrate proficiency in utilizing R and Excel to effectively explore and describe life science datasets.</p>
</div>
<div style="background-color: yellow; padding: 10px; border: 1px solid black;">
<p><strong>LO3</strong>. By the end of this course, students will be able to apply parametric and non-parametric statistical inference methods to experimental and observational data using RStudio and effectively interpret and communicate the results in the context of the data.</p>
</div>
<p>LO4. By the end ot this course, students will be able to put into practice both linear and non-linear models to describe relationships between variables using RStudio and Excel, demonstrating creativity in developing models that effectively represent complex data patterns.</p>
<div style="background-color: yellow; padding: 10px; border: 1px solid black;">
<p><strong>LO5</strong>. By the end of this course, students will be able to articulate statistical and modelling results clearly and convincingly in both written reports and oral presentations, working effectively as an individual and collaboratively in a team, showcasing the ability to convey complex information to varied audiences.</p>
</div>
</section>
<section id="inferential-statistics" class="slide level2">
<h2>Inferential statistics</h2>
<ul>
<li>So far we have focused on Exploratory Data Analysis <strong>EDA</strong>;</li>
<li><strong>EDA</strong> helps us describe and visualise data;</li>
<li><strong>Inferential statistics</strong> takes the next step: using a <strong>sample</strong> to learn about a <strong>population</strong>;</li>
<li>This is an important and sometimes difficult step in statistics;</li>
<li>Because samples vary by chance, we need formal methods to decide whether an observed difference is likely to reflect the real effect.</li>
</ul>
</section>
<section id="hypothesis-testing" class="slide level2">
<h2>Hypothesis testing</h2>
<ul>
<li>In statistics, a <strong>hypothesis</strong> is a claim about a population parameter.</li>
<li>We often begin with a <strong>benchmark</strong> or <strong>reference value</strong></li>
<li>We then ask:</li>
</ul>
<blockquote>
<p>Is our sample consistent with that claim, or is the difference too large to plausibly due to chance alone?</p>
</blockquote>
</section>
<section id="hypothesis-testing-1" class="slide level2">
<h2>Hypothesis testing</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Suppose the guideline value for Total Nitrogen (TN) at a site along a river is <span class="math inline">\(500 \mu g/L\)</span></li>
<li>We might ask</li>
</ul>
<blockquote>
<p>Is the mean TN concentration at this site equal to <span class="math inline">\(500 \mu g/L\)</span>, or is it different?</p>
</blockquote>
<ul>
<li>This gives us a natural hypothesis test:
<ul>
<li><strong>Null hypothesis</strong> <span class="math inline">\(H_0:\)</span> the mean TN concentration is <span class="math inline">\(500 \mu g/L\)</span></li>
<li><strong>Alternative hypothesis</strong> <span class="math inline">\(H_1:\)</span> the mean TN concentration is <strong>NOT</strong> <span class="math inline">\(500 \mu g/L\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/stream1.png"></p>
<figcaption>Grose River - Floris van Ogtrop</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="hypothesis-testing-workflow" class="slide level2">
<h2>Hypothesis testing workflow</h2>
<p><strong>We will follow the steps in hypothesis testing</strong></p>
<ol type="1">
<li>State the hypotheses;</li>
<li>Check assumptions;</li>
<li>Calculate the test statistic;</li>
<li>Obtain P-value, critical value, confidence intervals;</li>
<li>Draw the statistical conclusion;</li>
<li>Write a scientific (biological) conclusion.</li>
</ol>
</section>
<section id="hypothesis-testing-workflow-1" class="slide level2">
<h2>Hypothesis testing workflow</h2>
<p>A usefull acronym is <strong>HATPC</strong>:</p>
<ul>
<li><strong>H:</strong> Hypothesis</li>
<li><strong>A:</strong> Assumptions</li>
<li><strong>T:</strong> Test statistic</li>
<li><strong>P:</strong> P-Value</li>
<li><strong>C:</strong> Conclusion</li>
</ul>
</section>
<section id="h-hypothesis" class="slide level2">
<h2>H: Hypothesis</h2>
<ul>
<li>The <strong>null hypothesis</strong> <span class="math inline">\((H_0)\)</span> is the benchmark or reference claim</li>
<li>The <strong>alternative hypothesis</strong> <span class="math inline">\((H_1)\)</span> is the competing claim we are interested in.</li>
</ul>
<p>For example</p>
<ul>
<li><span class="math inline">\(H_0:\mu = 500 \mu g/L\)</span></li>
<li><span class="math inline">\(H_1:\mu \ne 500 \mu g/L\)</span></li>
</ul>
</section>
<section id="a-assumptions" class="slide level2">
<h2>A: Assumptions</h2>
<ul>
<li>Before carrying out a t-test, we need to check whether its assumptions are reasonable;</li>
<li>For a one sample t-test, an important assumption is that the sample data is approximately normally distributed.</li>
<li>We usually check this by:</li>
</ul>
<ol type="1">
<li>looking at the data using plots</li>
<li>Checking for strong skewness or outliers</li>
<li>Optionally using a formal test such as the Shapiro-Wilk test</li>
</ol>
</section>
<section id="t-test-statistic" class="slide level2">
<h2>T: Test Statistic</h2>
<p>A test statistic measure show far the observed result is from what we would expect under the null hypothesis.</p>
<p><span class="math inline">\(\text{Test statistic}=\frac{\text{Observed value - Expected value}}{\text{Standard error}}\)</span></p>
<p>This is essentially</p>
<p><span class="math inline">\(=\frac{\text{Signal}}{\text{Noise}}\)</span></p>
<ul>
<li><strong>Numerator</strong> = difference from the null value</li>
<li><strong>Denominator</strong> = uncertainty in that estimate</li>
</ul>
</section>
<section id="p-p-value" class="slide level2">
<h2>P: p-value</h2>
<ul>
<li>The <strong>p-value</strong> tells us how unusual our results would be <strong>if the null hypothesis were true</strong></li>
</ul>
<p>More formally:</p>
<ul>
<li>It is the probability of observing the test statistic, or something more extreme, assuming <span class="math inline">\(H_0\)</span> is true.</li>
</ul>
<p>So the p-value helps us judge whether the data are <strong>consistent with</strong> the null hypothesis.</p>
</section>
<section id="p-p-value-1" class="slide level2">
<h2>P: p-value</h2>
<p><strong>What does this have to do with sampling distributions??</strong></p>

<img data-src="images/two_tail.png" class="r-stretch"></section>
<section id="p-p-value-2" class="slide level2">
<h2>P: p-value</h2>
<p>A useful memory aid is:</p>
<p><strong>“If the P-value is low the Null hypothesis must go.”</strong></p>
<p>But more formally:</p>
<ul>
<li>If <span class="math inline">\(p &lt; 0.05\)</span> the data provide evidence against <span class="math inline">\(H_0\)</span></li>
<li>If <span class="math inline">\(p \ge 0.05\)</span> the data do not provide strong evidence against <span class="math inline">\(H_0\)</span></li>
</ul>
<p>Important:</p>
<ul>
<li>We <strong>do not accept</strong> <span class="math inline">\(H_0\)</span></li>
<li>We say <strong>we fail to reject</strong> <span class="math inline">\(H_0\)</span></li>
</ul>
</section>
<section id="p-p-value-3" class="slide level2">
<h2>P: p-value</h2>
<p><strong>Common mistakes</strong></p>
<ul>
<li>The p-value is not the chance that the NULL hypothesis is true</li>
<li>A large p-value does not mean that <span class="math inline">\(H_0\)</span> is true</li>
</ul>

<img data-src="images/p_value.png" class="r-stretch"><ul>
<li>The use of 0.05 is not mandatory, it is a convention.</li>
<li>Other levels such as 0.01 or 0.001 may also be used.</li>
</ul>
</section>
<section id="p-p-value-4" class="slide level2">
<h2>P: p-value</h2>
<p><strong>Controversy</strong></p>
<p><a href="https://www.nature.com/news/statisticians-issue-warning-over-misuse-of-p-values-1.19503">Nature article 1</a></p>
<p><a href="https://www.nature.com/articles/d41586-019-00857-9">Nature article 2</a></p>
<ul>
<li>Should we move away from an over reliance on p-values towards more robust statistical methods and a greater emphasis on the size and reproducibility of effects?</li>
<li>Look up terms like <strong>“P Hacking”</strong>…</li>
</ul>
</section>
<section id="c-conclusion" class="slide level2">
<h2>C: Conclusion</h2>
<p>At the end of a statistical test we write two conclusions</p>
<ol type="1">
<li>A <strong>statistical conclusion</strong> based on the test statistic, confidence intervals, p-value and the level of significance i.e.&nbsp;we reject or fail to reject <span class="math inline">\(H_0\)</span></li>
<li>A <strong>scientific (biological) conclusion</strong> what does this mean in the context of the study.</li>
</ol>
</section>
<section id="one-or-two---tails" class="slide level2">
<h2>One or Two - Tails</h2>

<img data-src="images/tails.png" class="r-stretch"></section>
<section id="one-or-two---tails-1" class="slide level2">
<h2>One or Two - Tails</h2>
<ul>
<li><p>Suppose we want to compare a sample population or sample mean <span class="math inline">\((\mu)\)</span> to a benchmark value <span class="math inline">\((c)\)</span> - Could be our water quality benchmark of <span class="math inline">\(c=500 \mu g/L\)</span></p>
<ul>
<li><p><span class="math inline">\(H_0:\mu=c\)</span> <em>Two tailed</em></p></li>
<li><p><span class="math inline">\(H_1:\mu \ne c\)</span> <em>Two tailed</em></p></li>
<li><p><span class="math inline">\(H_0:\mu \ge c\)</span> <em>One tailed - greater than</em></p></li>
<li><p><span class="math inline">\(H_1:\mu &lt; c\)</span> <em>One tailed - greater than</em></p></li>
<li><p><span class="math inline">\(H_0:\mu \le c\)</span> <em>One tailed - less than</em></p></li>
<li><p><span class="math inline">\(H_1:\mu &gt; c\)</span> <em>One tailed - less than</em></p></li>
</ul></li>
<li><p>We usually use the first (two tailed) form unless we are specifically interested in testing whether the difference is in one direction because this is the only direction of interest</p></li>
</ul>
</section>
<section id="one-tailed-tests-water-quality" class="slide level2">
<h2>One-tailed tests (water quality)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Goal</th>
<th>Hypotheses</th>
<th>Tail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Detect unsafe water</td>
<td>H₀: μ ≤ c, H₁: μ &gt; c</td>
<td>Right</td>
</tr>
<tr class="even">
<td>Demonstrate safe water</td>
<td>H₀: μ ≥ c, H₁: μ &lt; c</td>
<td>Left</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Rule:</strong> The tail follows the alternative hypothesis (H₁)</p>
</blockquote>
</section>
<section id="type-one-or-type-two-error" class="slide level2">
<h2>Type one or type two error</h2>
<p><strong>Type I error</strong></p>
<ul>
<li>False positive: we reject H0 when it is true</li>
</ul>
<p><strong>Type II error</strong></p>
<ul>
<li>False negative: we accept H0 when it is false</li>
</ul>

<img data-src="images/error.png" class="r-stretch"><p><strong>Note:</strong> Decreasing the significance level (<span class="math inline">\(\alpha\)</span>) to say 0.01 will increase the probability of type II error</p>
</section>
<section id="sample-size-and-power" class="slide level2">
<h2>Sample size and power</h2>
<p><strong>Power</strong> is the probability a test will detect a real effect when one exists.</p>
<ul>
<li><strong>High power</strong> means a low chance of type II error;</li>
<li><strong>Low power</strong> means a higher chance of missing a real effect.</li>
</ul>
<p>In general:</p>
<ul>
<li>larger sample sizes increase power;</li>
<li>smaller standard deviations increase power;</li>
<li>larger effects are easier to detect.</li>
</ul>
</section>
<section id="the-t-distribution" class="slide level2">
<h2>The t-distribution</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>The t-distribution is:</p>
<ul>
<li>bell-shaped;</li>
<li>symmetric;</li>
<li>centred on zero;</li>
<li>similar in shape to the normal distribution, but with <strong>heavier tails</strong>.</li>
</ul>
<p>Its exact shape depends on the <strong>degrees of freedom</strong></p>
<ul>
<li>For a one-sample t-test <span class="math inline">\(df=n-1\)</span> where n is the sample size.</li>
<li>As the sample size increases, the t-distribution becomes more similar to the normal distribution.</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/tdist.png"></p>
<figcaption>Comparing the shapes of the Student’s T and the Z (normal) curve</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="class-exercise-one-sample-t-test" class="slide level2">
<h2>Class exercise: One sample t-test</h2>
<p>Suppose we wish to test whether the mean resting heart rate of ENVX1002 students differs from a benchmark value of 70 beats per minute (bpm).</p>
<p>We are going to do this exercise in class but I have provided a simulated example below so you have it in the slides as well.</p>
</section>
<section id="class-exercise-one-sample-t-test-1" class="slide level2">
<h2>Class exercise: One sample t-test</h2>
<p>We will simulate some data for 30 students in our ENVX1002 class. To do this we will draw 30 random numbers from a normal distribution with a mean of 70 and a standard deviation of 10.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">set.seed</span>(<span class="dv">1974</span>)</span>
<span id="cb1-2"><a></a>heart_rate <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">70</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="class-exercise-hypothesis" class="slide level2">
<h2>Class exercise: <span style="color: blue;"><strong>H</strong></span>ypothesis</h2>
<p><strong>State the Null and Alternate hypothesis!</strong></p>
<ul>
<li><p><span class="math inline">\(H_0=70 \text{ bpm}\)</span> (Null hypothesis)</p></li>
<li><p><span class="math inline">\(H_1 \ne 70 \text{ bpm}\)</span> (Alternate hypothesis)</p></li>
</ul>
</section>
<section id="class-example-assumptions" class="slide level2">
<h2>Class example: <span style="color: blue;"><strong>A</strong></span>ssumptions</h2>
<p>Before applying a one-sample t-test, we should check whether the sample is approximately normally distributed. Consider the following:</p>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Sample size</th>
<th>Histogram</th>
<th>Q-Q plot</th>
<th>Jitter plot</th>
<th>Boxplot</th>
<th>Shapiro test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Small</strong> (<em>n</em> &lt; 30)</td>
<td>Limited</td>
<td><strong>Best</strong></td>
<td><strong>Very useful</strong></td>
<td><strong>Useful</strong></td>
<td>Cautious use</td>
</tr>
<tr class="even">
<td><strong>Medium</strong> (30–100)</td>
<td>Useful</td>
<td><strong>Very useful</strong></td>
<td>Useful</td>
<td>Useful</td>
<td>Sometimes useful</td>
</tr>
<tr class="odd">
<td><strong>Large</strong> (<em>n</em> &gt; 100)</td>
<td>Useful</td>
<td><strong>Best</strong></td>
<td>Less useful</td>
<td><strong>Good (outliers)</strong></td>
<td>Too sensitive</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Rule of thumb:</strong><br>
- Small <em>n</em>: <strong>show the data</strong> (jitter) + Q-Q plot<br>
- Larger <em>n</em>: <strong>histogram + Q-Q plot</strong><br>
- Use boxplots to highlight <strong>spread and outliers</strong>, not normality alone</p>
</blockquote>
</section>
<section id="class-example-assumptions-1" class="slide level2">
<h2>Class example: <span style="color: blue;"><strong>A</strong></span>ssumptions</h2>
<p>We begin by looking at the data (EDA). Ours sample size is 30 so we can look at the histogram, Q-Q plot and jitter plot.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a></a><span class="fu">library</span>(patchwork)</span>
<span id="cb2-3"><a></a></span>
<span id="cb2-4"><a></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(heart_rate)</span>
<span id="cb2-5"><a></a></span>
<span id="cb2-6"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(heart_rate)) <span class="sc">+</span></span>
<span id="cb2-7"><a></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"grey80"</span>, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram"</span>, <span class="at">x =</span> <span class="st">"Heart rate"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb2-10"><a></a></span>
<span id="cb2-11"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">sample =</span> heart_rate)) <span class="sc">+</span></span>
<span id="cb2-12"><a></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb2-13"><a></a>  <span class="fu">stat_qq_line</span>(<span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb2-14"><a></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Q-Q plot"</span>, <span class="at">x =</span> <span class="st">"Theoretical"</span>, <span class="at">y =</span> <span class="st">"Sample"</span>) <span class="sc">+</span></span>
<span id="cb2-15"><a></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb2-16"><a></a></span>
<span id="cb2-17"><a></a>p1 <span class="sc">+</span> p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lecture-05_files/figure-revealjs/unnamed-chunk-2-1.png" width="768" class="r-stretch"></section>
<section id="class-example-assumptions-2" class="slide level2">
<h2>Class example: <span style="color: blue;"><strong>A</strong></span>ssumptions</h2>
<p>As an option, we can also use the Shapiro-Wilk test as a supporting check. Best if the sample size is less than 50.</p>
<ul>
<li>If (p &gt; 0.05), we do not have strong evidence against normality;</li>
<li>This does not prove normality, but suggests the t-test may be reasonable.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">shapiro.test</span>(heart_rate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  heart_rate
W = 0.95114, p-value = 0.1814</code></pre>
</div>
</div>
</section>
<section id="class-example-test" class="slide level2">
<h2>Class example: <span style="color: blue;"><strong>T</strong></span>est</h2>
<p>For a one-sample t-test, the test statistic is:</p>
<p><span class="math inline">\(t = \frac{\bar{y} - \mu}{s/\sqrt{n}}\)</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\bar{y}\)</span> = sample mean</li>
<li><span class="math inline">\(\mu\)</span> = null (benchmark) value</li>
<li><span class="math inline">\(s\)</span> = sample standard deviation</li>
<li><span class="math inline">\(n\)</span> = sample size</li>
</ul>
</section>
<section id="class-example-test-1" class="slide level2">
<h2>Class example: <span style="color: blue;"><strong>T</strong></span>est</h2>
<p><span style="color: blue;"><strong>CI</strong></span> &amp; <span style="color: blue;"><strong>T</strong></span>-Statistic &amp; <span style="color: blue;"><strong>P</strong></span>-value</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>In R, the one-sample t-test gives us:</p>
<ul>
<li>the test statistic</li>
<li>degrees of freedom</li>
<li>the p-value</li>
<li>the confidence interval</li>
<li>the sample mean</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">t.test</span>(heart_rate,</span>
<span id="cb5-2"><a></a>  <span class="at">mu =</span> <span class="dv">70</span>,</span>
<span id="cb5-3"><a></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb5-4"><a></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb5-5"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  heart_rate
t = 0.25373, df = 29, p-value = 0.8015
alternative hypothesis: true mean is not equal to 70
95 percent confidence interval:
 66.76984 74.14513
sample estimates:
mean of x 
 70.45748 </code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>We can see the following output:</p>
<ul>
<li>the t-statistic = 0.25373</li>
<li>the degrees of freedom = 29 <span class="math inline">\((n-1)\)</span></li>
<li>the p-value = 0.8015</li>
<li>the 95% confidence interval = (66.76984 74.14513)</li>
<li>the sample mean = 70.45748</li>
</ul>
</div></div>
</section>
<section id="class-example-conclusion" class="slide level2">
<h2>Class example: <span style="color: blue;"><strong>C</strong></span>onclusion</h2>
<h3 id="statistical-conclusion">Statistical conclusion</h3>
<p>Because (p = 0.8015 &gt; 0.05), we <strong>fail to reject the null hypothesis</strong>.</p>
<h3 id="scientific-conclusion">Scientific conclusion</h3>
<p>The data do not provide strong evidence that the mean resting heart rate of ENVX1002 students differs from 70 bpm.</p>
<p>Also note: - 70 bpm lies within the 95% confidence interval - this is consistent with the non-significant test result</p>
</section>
<section id="confidence-intervals" class="slide level2">
<h2>Confidence intervals</h2>
<p>A <strong>confidence interval</strong> gives a range of plausible values for an unknown population parameter.</p>
<p>Many people prefer confidence intervals because they show:</p>
<ul>
<li>the estimated value</li>
<li>the uncertainty around that estimate</li>
</ul>
<p>A hypothesis test gives a decision about a claim. A confidence interval gives a plausible range.</p>
</section>
<section id="confidence-intervals---known-variance" class="slide level2">
<h2>Confidence intervals - known variance</h2>
<ul>
<li>Assuming our sample comes from a normal population, we can calculate the confidence interval for the mean of a population when the population <strong>variance is known</strong>. An example may be in manufacturing where we know the variance of a process.</li>
<li>The formula for the confidence interval is:</li>
</ul>
<p><span class="math inline">\(CI = \bar{y} \pm Z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}\)</span></p>
<p>for the 95% confidence interval, <span class="math inline">\(\alpha = 0.05\)</span> and <span class="math inline">\(Z_{\alpha/2} = 1.96\)</span> i.e.&nbsp;2 standard errors from the mean.</p>
</section>
<section id="confidence-intervals---unknown-variance" class="slide level2">
<h2>Confidence intervals - Unknown variance</h2>
<p>In practice, we usually do <strong>not</strong> know the population variance.</p>
<p>In that case, we use the t-distribution:</p>
<p><span class="math inline">\(CI = \bar{y} \pm t_{\alpha/2,df}\frac{s}{\sqrt{n}}\)</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(s\)</span> is the sample standard deviation</li>
<li><span class="math inline">\(df = n - 1\)</span></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">29</span>) <span class="do">## in our heart rate example, n=30 so df = 29 </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.04523</code></pre>
</div>
</div>
</section>
<section id="confidence-intervals---unknown-variance-1" class="slide level2">
<h2>Confidence intervals - Unknown variance</h2>
<ul>
<li>The following is simulation of 100 studies, each containing n = 6 observations of a fictitious toxic substance concentration (<span class="math inline">\(\mu g / l\)</span>) assumed to be <span class="math inline">\(\sim N(0.3, 0.12)\)</span>.</li>
<li>For each sample the 95% confidence interval calculated:</li>
</ul>

<img data-src="images/CI_sim.png" class="r-stretch quarto-figure-center"><p class="caption">Depiction of confidence intervals from each of 100 simulated samples</p></section>
<section id="confidence-intervals---unknown-variance-2" class="slide level2">
<h2>Confidence intervals - Unknown variance</h2>
<ul>
<li>In the graph on the previous slide, a confidence interval includes the true mean value of 0.3 if the vertical line (representing the width of the CI) crosses the horizontal line.</li>
<li>We have to accept that 5% of the time we will not capture the true mean.</li>
<li>We can widen the confidence interval to 99% so we are more confident but this can increase the chance of a type II error.</li>
</ul>
</section>
<section id="example-2-water-quality" class="slide level2">
<h2>Example 2: Water Quality</h2>
<p>Let’s look at our water quality example again:</p>
<ul>
<li>The data is Total Nitrogen (TN) levels @ Wallacia in western Sydney on the Nepean River</li>
<li>According to the ANZECC guidelines, the maximum acceptable level of TN in an lowland river is 500 <span class="math inline">\(\mu g/L\)</span> and for an upland river = 250 <span class="math inline">\(\mu g/l\)</span>. (see Table 3.3.2 in Australian and New Zealand Guidelines for Fresh and Marine Water Quality)</li>
<li>We want to know if the observed mean value of TN in our sample is different to the guideline value of 500 <span class="math inline">\(\mu g/L\)</span></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>TN <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/TN_Wallacia.csv"</span>)</span>
<span id="cb9-2"><a></a><span class="fu">str</span>(TN)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   29 obs. of  1 variable:
 $ TN: int  1020 1120 1170 920 920 1010 850 910 800 710 ...</code></pre>
</div>
</div>
</section>
<section id="example-2-water-quality-1" class="slide level2">
<h2>Example 2: Water Quality</h2>
<p><strong>State Hypothesis</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="math inline">\(H_0: \mu = 500\)</span> <span class="math inline">\(\mu g/l\)</span> (Null hypothesis)</li>
<li><span class="math inline">\(H_1: \mu \ne 500\)</span> <span class="math inline">\(\mu g/l\)</span> (Alternate hypothesis)</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/stream1.png"></p>
<figcaption>Grose River - Floris van Ogtrop</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="example-2-water-quality-2" class="slide level2">
<h2>Example 2: Water Quality</h2>
<p><strong>Check assumptions</strong></p>
<p>What do we notice about the plots? Does the data look normally distributed? Do we see strong skewness or outliers?</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb11-3"><a></a></span>
<span id="cb11-4"><a></a><span class="co"># Histogram</span></span>
<span id="cb11-5"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(TN, <span class="fu">aes</span>(<span class="at">x =</span> TN)) <span class="sc">+</span></span>
<span id="cb11-6"><a></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb11-7"><a></a>    <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb11-8"><a></a>    <span class="at">bins =</span> <span class="dv">7</span></span>
<span id="cb11-9"><a></a>  ) <span class="sc">+</span></span>
<span id="cb11-10"><a></a>  <span class="fu">xlab</span>(<span class="st">"Total Nitrogen (ug/L)"</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb11-12"><a></a></span>
<span id="cb11-13"><a></a><span class="co"># Boxplot</span></span>
<span id="cb11-14"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(TN, <span class="fu">aes</span>(<span class="at">x =</span> TN)) <span class="sc">+</span></span>
<span id="cb11-15"><a></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb11-16"><a></a>  <span class="fu">xlab</span>(<span class="st">"Total Nitrogen (ug/L)"</span>) <span class="sc">+</span></span>
<span id="cb11-17"><a></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb11-18"><a></a></span>
<span id="cb11-19"><a></a><span class="co"># Q-Q plot</span></span>
<span id="cb11-20"><a></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(TN, <span class="fu">aes</span>(<span class="at">sample =</span> TN)) <span class="sc">+</span></span>
<span id="cb11-21"><a></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb11-22"><a></a>  <span class="fu">stat_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb11-23"><a></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="co"># Arrange the plots in a 2x2 layout</span></span>
<span id="cb12-2"><a></a><span class="fu">grid.arrange</span>(p1, p2, p3, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture-05_files/figure-revealjs/unnamed-chunk-8-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-2-check-assumptions" class="slide level2">
<h2>Example 2: Check assumptions</h2>
<p><strong>Shapiro-Wilk normality test</strong></p>
<ul>
<li>For smaller sample sizes, we can use the Shapiro-Wilk test (say &lt; 50) to confirm whether the data is normally distributed or not.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">shapiro.test</span>(TN<span class="sc">$</span>TN)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  TN$TN
W = 0.92582, p-value = 0.04293</code></pre>
</div>
</div>
<ul>
<li>We see P&lt;0.05 so we <strong>reject</strong> the null hypothesis that the data is normally distributed.</li>
<li>For really large samples (&gt;&gt;30) the central limit theorem suggests that the distribution of the sample means tends to be normal. However, extreme skewness, heavy tails, or outliers can still affect the test’s performance.</li>
</ul>
</section>
<section id="example-2-transformations" class="slide level2">
<h2>Example 2: Transformations</h2>
<p>For right (positive) skewed data, we can use a</p>
<ul>
<li><span class="math inline">\(1/x\)</span> inverse transformation for highly skewed data.</li>
<li><span class="math inline">\(\log_{10}\)</span> or <span class="math inline">\(\log_e\)</span> transformation for very skewed data.</li>
<li><span class="math inline">\(\sqrt{x}\)</span> square root transformation for moderately skewed data.</li>
</ul>
<p>For left (negative) skewed data (which is rare to find), we can “try” a</p>
<ul>
<li><span class="math inline">\(x^2\)</span>, <span class="math inline">\(x^3\)</span> or <span class="math inline">\(e^x\)</span> transformation.</li>
</ul>
</section>
<section id="example-2-transformations-recheck-assumptions" class="slide level2">
<h2>Example 2: Transformations &amp; Recheck assumptions</h2>
<p>Let’s try a log10 transformation:</p>
<ul>
<li>We start by creating a new column in our data frame called log10_TN</li>
<li>We then take the log10 of the TN column and store it in the new column - note we could also use “mutate” from the dplyr package to do this.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>TN<span class="sc">$</span>log10_TN <span class="ot">&lt;-</span> <span class="fu">log10</span>(TN<span class="sc">$</span>TN)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="example-2-recheck-assumptions" class="slide level2">
<h2>Example 2: Recheck assumptions</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb16-2"><a></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb16-3"><a></a></span>
<span id="cb16-4"><a></a><span class="co"># Histogram</span></span>
<span id="cb16-5"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(TN, <span class="fu">aes</span>(<span class="at">x =</span> log10_TN)) <span class="sc">+</span></span>
<span id="cb16-6"><a></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb16-7"><a></a>    <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb16-8"><a></a>    <span class="at">bins =</span> <span class="dv">7</span></span>
<span id="cb16-9"><a></a>  ) <span class="sc">+</span></span>
<span id="cb16-10"><a></a>  <span class="fu">xlab</span>(<span class="st">"Log10 Total Nitrogen (ug/L)"</span>) <span class="sc">+</span></span>
<span id="cb16-11"><a></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb16-12"><a></a></span>
<span id="cb16-13"><a></a><span class="co"># Boxplot</span></span>
<span id="cb16-14"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(TN, <span class="fu">aes</span>(<span class="at">x =</span> log10_TN)) <span class="sc">+</span></span>
<span id="cb16-15"><a></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb16-16"><a></a>  <span class="fu">xlab</span>(<span class="st">"log10 Total Nitrogen (ug/L)"</span>) <span class="sc">+</span></span>
<span id="cb16-17"><a></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb16-18"><a></a></span>
<span id="cb16-19"><a></a><span class="co"># Q-Q plot</span></span>
<span id="cb16-20"><a></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(TN, <span class="fu">aes</span>(<span class="at">sample =</span> log10_TN)) <span class="sc">+</span></span>
<span id="cb16-21"><a></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb16-22"><a></a>  <span class="fu">stat_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb16-23"><a></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="co"># Arrange the plots in a 2x2 layout</span></span>
<span id="cb17-2"><a></a><span class="fu">grid.arrange</span>(p1, p2, p3, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture-05_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-2-recheck-assumptions-1" class="slide level2">
<h2>Example 2: Recheck assumptions</h2>
<p><strong>Shapiro-Wilk normality test</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">shapiro.test</span>(TN<span class="sc">$</span>log10_TN)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  TN$log10_TN
W = 0.97279, p-value = 0.6375</code></pre>
</div>
</div>
<ul>
<li>From our previous slide, our data seems to be quite symmetrical</li>
<li>Now P&gt;0.05 so we <strong>fail to reject</strong> the null hypothesis that the data is normally distributed.</li>
<li>We can now proceed with our t-test using the log transformed data.</li>
</ul>
</section>
<section id="example-2-restate-the-hypotheses" class="slide level2">
<h2>Example 2: Restate the hypotheses</h2>
<ul>
<li><p>We will also need to transform the hypothesised mean of 500 to the log10 scale.</p></li>
<li><p><span class="math inline">\(H_0: \mu = log10(500)\)</span> <span class="math inline">\(\mu g/l\)</span> (Null hypothesis)</p></li>
<li><p><span class="math inline">\(H_1: \mu \ne log10(500)\)</span> <span class="math inline">\(\mu g/l\)</span> (Alternate hypothesis)</p></li>
</ul>
</section>
<section id="example-2-t-test-p-value" class="slide level2">
<h2>Example 2: T-test &amp; P-Value</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">t.test</span>(TN<span class="sc">$</span>log10_TN,</span>
<span id="cb20-2"><a></a>  <span class="at">mu =</span> <span class="fu">log10</span>(<span class="dv">500</span>),</span>
<span id="cb20-3"><a></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb20-4"><a></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb20-5"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  TN$log10_TN
t = 4.8768, df = 28, p-value = 3.884e-05
alternative hypothesis: true mean is not equal to 2.69897
95 percent confidence interval:
 2.807748 2.965309
sample estimates:
mean of x 
 2.886528 </code></pre>
</div>
</div>
<ul>
<li>The p-value is &lt;0.001 (3.d.p.) which is less than 0.05. Therefore, we reject the null hypothesis.</li>
<li>There is strong evidence that the mean value of TN in Nepean River is different to 500 ug/L.</li>
<li>Can we say something about the direction??</li>
</ul>
</section>
<section id="example-2-geometric-mean-confidence-intervals" class="slide level2">
<h2>Example 2: Geometric mean &amp; Confidence intervals</h2>
<p><strong>Geometric mean</strong></p>
<p>Note that now we are looking at the geometric mean as opposed the the arithmatic mean which was 855.86 in our case</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="dv">10</span><span class="sc">^</span><span class="fu">mean</span>(TN<span class="sc">$</span>log10_TN)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 770.0666</code></pre>
</div>
</div>
<p><strong>Confidence intervals</strong></p>
<ul>
<li>We need to back transform the confidence interval to the original scale.</li>
<li>To back-transform the confidence interval we can use the following:</li>
</ul>
<p><span class="math inline">\(10^{CI_{low}}\)</span> and <span class="math inline">\(10^{CI_{high}}\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="dv">10</span><span class="sc">^</span>(<span class="fl">2.81</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 645.6542</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="dv">10</span><span class="sc">^</span>(<span class="fl">2.97</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 933.2543</code></pre>
</div>
</div>
<ul>
<li>This means that we are 95% confident that the geometric mean (back-transformed mean) of the sample is between approximately 646 and 933 ug/l. This is higher than the hypothesised mean.</li>
</ul>
</section>
<section id="example-2-conclusion" class="slide level2">
<h2>Example 2: Conclusion</h2>
<ol type="1">
<li>The data was log10 transformed to meet the assumptions of the t-test.</li>
<li>We have strong evidence that the mean value of Total Nitrogen in Nepean River is different to 500 ug/L.</li>
<li>We are 95% confident that the geometric mean (back-transformed mean) of the sample is between approximately 646 and 933 ug/l.</li>
<li>Looking at the confidence interval, we can say that the mean value of TN in Nepean River is significantly greater than 500 ug/L.</li>
</ol>
</section>
<section id="example-3-one-tailed-test" class="slide level2">
<h2>Example 3: One tailed test</h2>
<ul>
<li>We can also use a one tailed test if we are specifically interested in whether the observed value is greater or less than the expected value.</li>
<li>In this case we only want to know if the TN concentration is greater than the ANZECC guidelines of 500 <span class="math inline">\(\mu g/l\)</span>.</li>
</ul>
<blockquote>
<p>Detect unsafe water | H₀: μ ≤ 500, H₁: μ &gt; 500 |</p>
</blockquote>
<p>OR</p>
<blockquote>
<p>Detect unsafe water | H₀: μ ≤ <span class="math inline">\(log_{10}500\)</span>, H₁: μ &gt; <span class="math inline">\(log_{10}500)\)</span> |</p>
</blockquote>
</section>
<section id="example-3-one-tailed-test-1" class="slide level2">
<h2>Example 3: One tailed test</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">t.test</span>(TN<span class="sc">$</span>log10_TN,</span>
<span id="cb28-2"><a></a>  <span class="at">mu =</span> <span class="fu">log10</span>(<span class="dv">500</span>),</span>
<span id="cb28-3"><a></a>  <span class="at">alternative =</span> <span class="st">"greater"</span>,</span>
<span id="cb28-4"><a></a>  <span class="at">conf.level =</span> <span class="fl">0.95</span></span>
<span id="cb28-5"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  TN$log10_TN
t = 4.8768, df = 28, p-value = 1.942e-05
alternative hypothesis: true mean is greater than 2.69897
95 percent confidence interval:
 2.821104      Inf
sample estimates:
mean of x 
 2.886528 </code></pre>
</div>
</div>
<ul>
<li>P &lt; 0.001 (3.d.p.) so we reject the null hypothesis.</li>
<li>Because we are doing a one tailed test we can now conclude that the mean value of TN in Nepean River is greater than <span class="math inline">\(log_{10}500 \mu g/L\)</span></li>
<li>Take a look at the confidence interval and the p-value. What do you notice when comparing to the two tailed test?</li>
</ul>
</section>
<section id="example-3-one-tailed-test-2" class="slide level2">
<h2>Example 3: One tailed test</h2>
<p><a href="https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2010.00014.x">Ruxton and Neuhäuser 2010</a></p>

<img data-src="images/one_tail.png" class="r-stretch"></section></section>
<section id="references" class="title-slide slide level1 center">
<h1>References</h1>
<ul>
<li>Quinn G. P. &amp; Keough M. J. (2002) Experimental design and data analysis for biologists. Cambridge University Press, Cambridge, UK.</li>
<li>Logan, M. (2010). Biostatistical design and analysis using R a practical guide. Hoboken, N.J., Wiley-Blackwell.</li>
<li>Fox, G. A., S. Negrete-Yankelevich, and V. J. Sosa. (2015). Ecological statistics: contemporary theory and application. Oxford University Press, USA</li>
<li>Ruxton, G.D. and Neuhäuser, M., 2010. When should we use one-tailed hypothesis testing? Methods in Ecology and Evolution, 1 (2), 114-117.</li>
</ul>
</section>

<section id="thanks" class="title-slide slide level1 center">
<h1>Thanks!</h1>
<p>This presentation is based on the <a href="https://github.com/usyd-soles-edu/soles-revealjs">SOLES Quarto reveal.js template</a> and is licensed under a <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p>
<!-- Links -->


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>