---
title: ENVX1002 -- Introduction to statistical methods
author: 
  - Januar Harianto
  - Liana Pozza
  - Si Yang Han
  - Floris Van Ogtrop (coordinator)
anchor-sections: false
section-divs: false
---

**This site contains the lecture material for ENVX1002.** It is meant for lecturers to publish their lecture content in a structured way and has not been designed for student use. Most of the content is still in development and will be updated throughout the semester. If you happen to stumble upon this site, feel free to have a look around... but be aware that the content is *not* final and may contain errors.

**ENVX1002 students should always navigate to [Canvas](https://canvas.sydney.edu.au/) to access the ENVX1002 page and view the course material in the right context.**


### Module 1 -- describing data
- [Lecture 01](lectures/L01/index.qmd) -- Reproducible science
- [Lecture 02](lectures/L02/index.qmd) -- Introduction to statistical programming
- [Lecture 03](lectures/L03/index.qmd) -- Exploring and visualising data
- [Lecture 04](lectures/L04/index.qmd) -- The central limit theorem

### Module 2 -- inference
- [Lecture 05](lectures/L05/index.qmd) -- Hypothesis testing & one-sample *t*-tests
- [Lecture 06](lectures/L06/index.qmd) -- Two-sample *t*-tests
- [Lecture 07](lectures/L07/index.qmd) -- Non-parametric tests
- [Lecture 08](lectures/L08/index.qmd) -- Bootstrapping | Revision

### Module 3 -- modelling
- [Lecture 09](lectures/L09/index.qmd) -- Describing relationships
- [Lecture 10](lectures/L10/index.qmd) -- Linear functions
- [Lecture 11](lectures/L11/index.qmd) -- Linear functions - multiple predictors
- [Lecture 12](lectures/L12/index.qmd) -- Non-linear functions

