{
  "hash": "951852603c753fdf682c7b9720ac133a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Topic 6 -- Two-sample *t*-tests -- Part II\"\nauthor: Januar Harianto\nformat: soles-revealjs\nembed-resources: true\n---\n\n\n\n\n# When assumptions of the *t*-test are violated\n\n## Recap: Assumptions of the two-sample *t*-test\n\n### With independent samples:\n\n- **Normality**: the data are normally distributed\n- **Homogeneity of variance** (equal variances): the variances of the two groups are equal\n\n### With paired samples:\n\n- **Normality**: the differences between the paired samples are normally distributed\n- Equal variances is implied\n\n## If we analyse the data anyway...\n\nThe *t*-test:\n\n- may provide incorrect results as **mean and variance calculations depend on normally distributed data**.\n- may be **less powerful** (i.e., less likely to detect a true difference).\n- may be **biased** (i.e., systematically over- or under-estimating the true difference).\n\n# Don't throw the data away...\n\n## What can we do?\n\nThe *t*-test is quite robust to violations of normality, especially when the sample size is large. However, the assumption of equal variances is more critical – we cannot simply depend on large sample sizes to \"fix\" the problem.\n\nOptions include:\n\n- **Transform** the data to normalise the data and/or scale the variance\n- Use a **Welch's *t*-test** or a **Welch's ANOVA** (limited cases)\n- Use a **non-parametric test**, such as the **Mann-Whitney U test** or **Wilcoxon signed-rank test** (paired samples) -- however, these tests have *less power* than the *t*-test i.e. less likely to detect a true difference.\n\n\n# Ants - a foraging biomass study\n\n![*Formica rufa*, the horse ant - native to Eurasia.](images/formica_rufa.jpg) {fig-align=\"left\"}\n\n## Is the food collected by ants different between two sites?\n\n### Data structure\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 54\nColumns: 2\n$ Food <dbl> 11.9, 33.3, 4.6, 5.5, 6.2, 11.0, 24.3, 20.7, 5.7, 12.6, 10.2, 4.7…\n$ Tree <fct> Rowan, Rowan, Rowan, Rowan, Rowan, Rowan, Rowan, Rowan, Rowan, Ro…\n```\n\n\n:::\n:::\n\n\n\n\nWe want to compare the mean biomass of food, collected by ants between the two sites in **dry weight (mg) of prey, divided by the total number of ants leaving the tree in 30 minutes**.\n\n## Visualising the data\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-06b-2s-ttest-2_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n\nDoes this data meet the assumptions of the two-sample *t*-test?\n\n## Checking assumptions\n\nWe have some idea that the data may not be normally distributed, but are not quite sure. So let's check using the Q-Q plot.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-06b-2s-ttest-2_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n\n\n::: incremental\n- Curvature of the data points away from the line indicates non-normality.\n- Boxplots (previous slide) suggest equal variances.\n- **Let's transform the data.**\n:::\n\n\n\n## Picking a transformation\n\nWe need to consider the **type of data** and the **shape of its distribution** when choosing a transformation. These can be assessed using:\n\n::: incremental\n- **Histograms** and **Q-Q plots** to assess normality - DONE\n- **Box plots** to assess homogeneity of variance - DONE\n- **Skewness** and **kurtosis** to assess the shape of the distribution - NEXT\n:::\n\n\n## Skewness\n\nThe degree of asymmetry in the data distribution when compared to a normal distribution.\n\n::: fragment\n- Represented by the **skewness coefficient** ($\\gamma_1$) and can be positive, negative, or zero.\n- Skewness values between **-0.5 and 0.5** are considered acceptable (fairly symmetrical).\n- **Negative** skewness indicates a *left*-skewed distribution, while **positive** skewness indicates a *right*-skewed distribution.\n- Above 1 or below -1, the distribution is considered ***highly* skewed**.\n:::\n\n## Example: skewness\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-06b-2s-ttest-2_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n\n## Kurtosis\n\nUsed to describe the extreme values (outliers) in the distribution versus the tails.\n\n::: fragment\n- **High kurtosis (>3)** indicates a distribution with **heavy tails** and a **peaked centre**. When this happens, we should investigate the data for outliers.\n- **Low kurtosis (<3)** indicates a distribution with **light tails** and a **flat centre**. There are fewer to no outliers in the data.\n:::\n\n\n## Example: kurtosis\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-06b-2s-ttest-2_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n\n\n## Skewness and kurtosis in the ants data\n\nWith experience we can \"eyeball\" the data, but we can also calculate the skewness and kurtosis.\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Tree     skewness kurtosis\n  <fct>       <dbl>    <dbl>\n1 Rowan       1.04      3.15\n2 Sycamore    0.807     2.63\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-06b-2s-ttest-2_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n\n::: fragment\nFrom the results we can see that both sites have a **positive skewness**. Site `Rowan` has high kurtosis.\n:::\n\n\n\n# Data transformation\n\n\n\n## Workflow\n\n::: incremental\n1. Check the data for normality and homogeneity of variance (i.e. **test assumptions**). \n2. If the assumptions are violated, consider **transforming the data**.\n3. **Repeat** checks on assumptions. If assumptions are **met**, proceed with the *t*-test on the transformed scale. *Otherwise, use a different transformation or consider using a non-parametric test.*\n4. Interpret the statistical results and **back-transform the results** to the original scale (optional but recommended) to aid interpretation.\n:::\n\n\n## Picking a transformation\n\n::: fragment\n### For positive skewness\n\n- **Square root** transformation: $\\sqrt{x}$ for skewness between 0.5 and 1 and kurtosis < 3.\n- **Logarithmic** transformation: $\\log(x)$ for skewness > 1 and kurtosis < 3.\n- **Reciprocal** transformation: $\\frac{1}{x}$ for skewness > 1 and kurtosis > 3 (quite extreme).\n:::\n\n\n::: fragment\n### For negative skewness\n- This is rare as most biological data are positively skewed. However, you can try the **square** $x^2$ or **cube** $x^3$ transformation.\n- If negatively skewed data contains zeros, consider using the log transform and adding a constant to the data before transformation e.g. $\\log(x + 1)$.\n:::\n\n::: fragment\n::: callout-note\nThere is also the **Box-Cox transformation** which informs us of the best transformation to apply to the data without the need to check skewness and kurtosis. This method is not covered in this unit, but you can read more about it [here](https://r-coder.com/box-cox-transformation-r/) (the simple R version) or [here](https://en.wikipedia.org/wiki/Power_transform#Box%E2%80%93Cox_transformation) (more detailed mathematical explanation).\n:::\n:::\n\n## How do we check if the transformation worked?\n\nWe need to apply the transformation to the entire dataset and check the Q-Q plot again.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](lecture-06b-2s-ttest-2_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\n\n## Checking skewness and kurtosis after transformation\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Tree      skewness kurtosis\n  <fct>        <dbl>    <dbl>\n1 Rowan    0.271         1.77\n2 Sycamore 0.0000457     1.86\n```\n\n\n:::\n:::\n\n\n\n\n## Performing the *t*-test\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Food_log by Tree\nt = -2.0521, df = 52, p-value = 0.04521\nalternative hypothesis: true difference in means between group Rowan and group Sycamore is not equal to 0\n95 percent confidence interval:\n -0.732858080 -0.008203447\nsample estimates:\n   mean in group Rowan mean in group Sycamore \n              2.287756               2.658287 \n```\n\n\n:::\n:::\n\n\n\n\n\n::: fragment\n### How do we interpret the results?\n\nEvidence suggests that the log-transformed mean biomass of food collected by ants from the Rowan site is significantly different from the log-transformed mean biomass of food collected by ants from the Sycamore site (t = -2.05, df = 52, p = 0.045).\n:::\n\n\n## Back-transforming the results\n\n- For power transformations, we can back-transform the results to the original scale using the inverse function.\n- Log transformations are a bit tricky as the inverse function is the exponential function.\n  - For the natural log transformation which is `log()` in R, the inverse function is the exponential function: $e^x$.\n  - For the base 10 log transformation which is `log10()` in R, the inverse function is $10^x$.\n\n## Interpretation\n\n### Back-transforming mean values\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.448503\n```\n\n\n:::\n:::\n\n\n\n\n> Evidence suggests that the log-transformed mean biomass of food collected by ants from the Rowan site is significantly different from the log-transformed mean biomass of food collected by ants from the Sycamore site (t = -2.05, df = 52, p = 0.045).\n\nThe mean biomass of food collected by ants from the Sycamore site (14.3 mg) is 1.4 times greater than the mean biomass of food collected by ants from the Rowan site (9.9 mg).\n\n### Back-transforming confidence intervals\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4805336 0.9918301\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Comparing to a test without transformation\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Food by Tree\nt = -1.9217, df = 52, p-value = 0.06013\nalternative hypothesis: true difference in means between group Rowan and group Sycamore is not equal to 0\n95 percent confidence interval:\n -10.4916030   0.2267678\nsample estimates:\n   mean in group Rowan mean in group Sycamore \n              12.27143               17.40385 \n```\n\n\n:::\n:::\n\n\n\n\n:::: columns\n::: column\n- Original mean values: \n  - Rowan = 12.3 mg\n  - Sycamore = 17.4 mg\n- Log-transformed mean values: \n  - Rowan = 2.3 lg(mg)\n  - Sycamore = 2.7 lg(mg)\n- Back-transformed mean values: \n  - **Rowan = 9.9 mg**\n  - **Sycamore = 14.3 mg**\n  \n\nThe original mean values are based on the arithmetic mean, while the log-transformed mean values are based on the geometric mean. The geometric mean is more appropriate for skewed data.\n\n:::\n\n::: column\n- Original 95% confidence interval: \n  - -10.5 to 0.2 mg\n- Log-transformed 95% confidence interval:\n  - 0.5 to 1 lg(mg)\n- Back-transformed 95% confidence interval:\n  - **1.6 to 2.7 mg**\n\nThe influence of kurtosis on the 95% confidence interval is evident when comparing the original and back-transformed confidence intervals, as the log transform reduces the effect of outliers on the data.\n:::\n::::\n\n\n\n# Thanks!\n\nThis presentation is based on the [SOLES Quarto reveal.js template](https://github.com/usyd-soles-edu/soles-revealjs) and is licensed under a [Creative Commons Attribution 4.0 International License][cc-by].\n\n\n<!-- Links -->\n[cc-by]: http://creativecommons.org/licenses/by/4.0/",
    "supporting": [
      "lecture-06b-2s-ttest-2_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}