{
  "hash": "488f83d2689cbd98aec9274b0e081caf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Topic 3 -- Discrete Distributions\nauthor: Dr. Floris van Ogtrop\nformat: soles-revealjs\nembed-resources: true\n---\n\n\n\n\n\n\n# Outline – Discrete distributions\n\n- Example\n- What is a distribution\n- Binomial distribution\n- Poisson distribution\n\n\n\n\n\n# Learning outcomes\n\nAt the end of this topic students should able to:\n\n- Have a good understanding of what a distribution is\n  - Definitions\n  - Functions\n  - Binomial and Poisson distributions\n- Apply the correct model to describe data\n- Demonstrate proficiency in the use of R and Excel for calculating probabilities\n\n\n\n\n\n\n# Types of data\n\n**Remember the types of data**\n\n**Numerical**\n\n- Continuous:  yield, weight\n- Discrete:  weeds per $m^2$\n\n**Categorical**\n\n- Binary:  2 mutually exclusive categories \n- Ordinal:  categories ranked in order \n- Nominal:  qualitative data\n\n\n\n\n# Example\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n- We have 5 insects which we spray with an insecticide, each insect has a 60% chance of being killed;\n- $P(K) = 0.6$\n- Possible questions:\n  - What is the probability that all 5 insects will be killed?\n  - What is the probability that at least 3 insects will be killed?\n- The data is ‘binary’ and the events are mutually exclusive (either dead or alive unless it is zombie fly);\n  - we can say the data is categorical or numeric discrete \n  - we can use a binomial (discrete) distribution to \"model\" the data.\n\n:::\n::: {.column width=\"50%\"}\n\n![Generated using DALL.E3](images/L3_zombie_fly.png){width=80%}\n\n:::\n\n::::\n\n\n\n\n# What is a distribution?\n\n- In our case we are generally referring to a distribution function\n  - This is a function (or model) that describes the probability that a system will take on value or set of values {x}\n\n- For any variable X, we describe probabilities by\n  - Discrete variables: probability distribution function $P(X=x)$\n  - Continuous variables: probability density function $f(x)$\n  - Discrete and Continuous variables: cumulative density function \n$F(x) = P(X\\le{x})$ \n\n\n\n\n\n# Back to our example\n\n- We spray 5 flies with insecticide which has 60% chance of killing each insect. If $X$ is the number of flies that die, what is the distribution of $X$?\n- The set of possible values is $x=0,1,2,3,4,5$\n- The likelihood of each value is \n- $P(X=0)=P(\\text{no insects die})=0.4× 0.4× 0.4× 0.4× 0.4=0.4^5=0.01024$ \n- $P(X=1)=P(\\text{one insects die})=0.6× 0.4× 0.4× 0.4× 0.4 + 0.4× 0.6× 0.4× 0.4× 0.4 + 0.4× 0.4× 0.6× 0.4× 0.4 + 0.4× 0.4× 0.4× 0.6× 0.4 + 0.4× 0.4× 0.4× 0.4× 0.6 = 0.0768$\n- $P(X=2)=P(\\text{two insects die})=… \\text{10 different combinations} = 0.2304$\n- $P(X=3)=P(\\text{three insects die})=… \\text{10 different combinations} = 0.3456$\n- $P(X=4)=P(\\text{four insects die})=… \\text{5 combinations} = 0.2592$\n- $P(X=0)=P(\\text{all insects die})=0.6× 0.6× 0.6× 0.6× 0.6=0.65=0.07776$\n\n\n\n\n# Example plot\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0, 1, 2, 3, 4, 5)\np <- c(0.01024, 0.0768, 0.2304, 0.3456, 0.2592, 0.07776)\nplot(x, p, type = \"h\")\n```\n\n::: {.cell-output-display}\n![](lecture-03_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n# Example – properties of the distribution\n\n- Remember we have a binomial (dead or alive) distribution here\n- A key property of all (discrete) distributions is that all probabilities add to \n\n$\\Sigma_{i=0}^5P(X=i)=0.01024+0.0768+0.2304+0.3456+0.2592+0.07776=1$\n\n- Note that all probabilities lie between 0 and 1\n\n\n\n\n\n\n# Binomial Distribution\n\n- Why does a binomial distribution fit our insect data??\n  - Basic element is a Bernoulli trial – each insect;\n  - The outcome of each trial can be classified in precisely one of two mutually exclusive ways termed “success” (dead) and “failure” (alive);\n    - We usually assign **$p$** to success and $q$ to failure.\n  - Binomial experiments consists of n Bernouilli (independent binary) trials (i.e. 5 insects);\n  - The probability of a success, denoted by p, remains constant from trial to trial. The probability of a failure, $q =1 – p$;\n    - $p = 0.6$ and $q = 0.4$\n  - The trials are independent; that is, the outcome of any particular trial is not affected by the outcome of any other trial;\n  - The number of successes, x, is a binomial variable.\n  \n  \n  \n  \n  \n  \n# Example\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n- How many combinations are there for exactly 2 flies to die out of 5 flies?\n\n${5\\choose{2}}=\\frac{5!}{2!(5−2)!}= \\frac{(5×4×3×2×1)}{(2×1×3×2×1)}=10$\n\n- What is the probability that exactly 2 flies will die?\n\n$P(X=x)={n\\choose{x}}p^x(1-p)^{n-x}={5\\choose{2}}0.6^2(1-0.6)^{5-2}$\n\n$=10×0.36×0.064=0.2304$\n\n:::\n\n::: {.column width=\"50%\"}\n\n![](images/R_logo.jpg) - `dbinom(2,5,0.6)`\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(2,5,0.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2304\n```\n\n\n:::\n:::\n\n\n\n\n\n\n![](images/Excel_logo.jpg) - `=BINOM.DIST(2,5,0.6,FALSE)`\n\n:::\n::::\n\n\n\n\n# Point, cumulative or interval probabilities\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n- We have already calculated a point probability i.e. the probability of exactly 2 flies dying.\n- But what about if we wanted to know the probability of 2 or more flies dying $P(X\\ge{2})$ or between 2 and 4 flies $P(2\\le{X}\\le{4})$ dying??\n- So how can we calculate these?\n  - One way is to calculate all the point probabilities from 0-5 and add the probabilities cumulatively or in the interval\n\n:::\n\n::: {.column width=\"50%\"}\n![](images/L3_CumulativeP.png){width=\"50%\"} \n\n:::\n\n::::\n\n\n# Point, cumulative or interval probabilities\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n$P(X\\ge{2})=(X=2)+(X=3)+(X=4)+(X=5)=0.2304+0.3456+0.2592+0.07776=0.91296$\n \n- You guys try to calculate the following\n\n$P(2\\le{X}\\le{4})=??$\n\n\n:::\n\n::: {.column width=\"50%\"}\n![](images/L3_CumulativeP.png){width=\"50%\"} \n\n:::\n\n::::\n\n\n\n\n\n# Cumulative\n\n$P(X\\ge{2})$\n\n![](images/R_logo.jpg)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pbinom(1,5,0.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.91296\n```\n\n\n:::\n\n```{.r .cell-code}\n## OR\n\npbinom(1,5,0.6, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.91296\n```\n\n\n:::\n:::\n\n\n\n\n\n\n![](images/Excel_logo.jpg) - `=1-BINOM.DIST(1,5,0.6,TRUE)`\n\n\n\n\n\n# Interval\n\n$P(2 \\le X \\le 4)$\n\n![](images/R_logo.jpg)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(4,5,0.6)-pbinom(1,5,0.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8352\n```\n\n\n:::\n:::\n\n\n\n\n\n\n![](images/Excel_logo.jpg) - `=BINOM.DIST(4,5,0.6,TRUE)-BINOM.DIST(1,5,0.6,TRUE)`\n\n\n\n\n\n\n\n# Mean and variance of the binomial distribution\n\n- Mean binomial distribution \n\n$\\mu_x=np$\n\n$=5\\times{0.6} = 3$ On average 3 flies die in 5 trials\n\n- Variance binomial distribution\n\n$\\sigma_x^2=np(1-p)$\n\n$=5\\times{0.6}(1-0.6)=1.2$ with a variance of 1.2 flies\n\n\n\n\n\n\n# Count Data\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n- Often we are interested in count data such as the number of events occurring in an interval;\n- We generally model this data using the Poisson distribution (Described by Simeon-Denis Poisson) where we use $\\lambda$ denotes the average number of events occurring in an interval\n\n![Source: https://sharemylesson.com/teaching-resource/sesame-street-song-count-253315](images/L3_Count.png) \n\n:::\n\n::: {.column width=\"50%\"}\n\n- We often write this as \n\n$X\\sim{Po(\\lambda)}$\n\n- Where $X$ is the number of discrete and independent events in the interval\n  - e.g. number of plants of a certain species along transect\n  - e.g. occurrence of disease in a period of time\n\n\n\n:::\n\n::::\n\n\n\n\n\n\n# Horse kick deaths in the Prussian Army\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\nkick <- read.csv(\"data/Kick_deaths.csv\")\nkable(kick[1:12,])\n```\n\n::: {.cell-output-display}\n\n\n| Year| GC| C1| C2| C3| C4| C5| C6| C7| C8| C9| C10| C11| C14| C15|\n|----:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|---:|---:|---:|---:|\n| 1875|  0|  0|  0|  0|  0|  0|  0|  1|  1|  0|   0|   0|   1|   0|\n| 1876|  2|  0|  0|  0|  1|  0|  0|  0|  0|  0|   0|   0|   1|   1|\n| 1877|  2|  0|  0|  0|  0|  0|  1|  1|  0|  0|   1|   0|   2|   0|\n| 1878|  1|  2|  2|  1|  1|  0|  0|  0|  0|  0|   1|   0|   1|   0|\n| 1879|  0|  0|  0|  1|  1|  2|  2|  0|  1|  0|   0|   2|   1|   0|\n| 1880|  0|  3|  2|  1|  1|  1|  0|  0|  0|  2|   1|   4|   3|   0|\n| 1881|  1|  0|  0|  2|  1|  0|  0|  1|  0|  1|   0|   0|   0|   0|\n| 1882|  1|  2|  0|  0|  0|  0|  1|  0|  1|  1|   2|   1|   4|   1|\n| 1883|  0|  0|  1|  2|  0|  1|  2|  1|  0|  1|   0|   3|   0|   0|\n| 1884|  3|  0|  1|  0|  0|  0|  0|  1|  0|  0|   2|   0|   1|   1|\n| 1885|  0|  0|  0|  0|  0|  0|  1|  0|  0|  2|   0|   1|   0|   1|\n| 1886|  2|  1|  0|  0|  1|  1|  1|  0|  0|  1|   0|   1|   3|   0|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n# Horse kick deaths in the Prussian Army\n\nhttps://en.wikipedia.org/wiki/Ladislaus_Bortkiewicz \n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nfrequency_kick <- kick %>%\n  select(-Year) %>%\n  pivot_longer(cols = everything(), names_to = \"Column\", values_to = \"Deaths\") %>%\n  count(Deaths) %>%\n  arrange(Deaths) %>%\n  mutate(Total_Deaths = Deaths*n) %>%\n  mutate(Probability = \"?\")\n\nkable(frequency_kick)\n```\n\n::: {.cell-output-display}\n\n\n| Deaths|   n| Total_Deaths|Probability |\n|------:|---:|------------:|:-----------|\n|      0| 144|            0|?           |\n|      1|  91|           91|?           |\n|      2|  32|           64|?           |\n|      3|  11|           33|?           |\n|      4|   2|            8|?           |\n\n\n:::\n:::\n\n\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n- What is the Probability in any month of \n  - 0 injuries by horse kick \n  - 1 injuries by horse kick\n  - 2 injuries by horse kick \n  - 3 injuries by horse kick \n  - 4 injuries by horse kick\n- $\\lambda$ “Lambda” is the mean\n\n:::\n\n::::\n\n\n\n\n\n# Horse kick deaths in the Prussian Army\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_kick <- frequency_kick %>% \n  summarize(n = sum(n), sum_Total_Deaths = sum(Total_Deaths))\n\nkable(total_kick)\n```\n\n::: {.cell-output-display}\n\n\n|   n| sum_Total_Deaths|\n|---:|----------------:|\n| 280|              196|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n# Poisson Distribution\n\n$X\\sim{Po(\\lambda)}$\n\n$P(X=x)=\\frac{\\lambda^x e^{-\\lambda}}{x!}$ $x=0,1,2,...$ $\\lambda>0$\n\n- Note that $e$ denotes the exponential function such that\n  - $e^0=1$\n  - $e^-2=0.135 \\text{(3 d.p.)}$\n  - $e^-10=4.540\\times 10^{−5} \\text{(3 d.p.)}$\n  \n  \n\n\n\n\n# Example with kick deaths\n\n- We first identify the model\n  - $X$ = the number of soldiers injured by horse kick $\\sim{Po(\\lambda)}$ where $\\lambda$ = the average number of deaths = $196/280 = 0.7$. We can now calculate the probability of having exactly 0, 1, 2, 3, 4, 5 deaths\n\n- $P(X=0)=\\frac{0.7^0 e^{-0.7}}{0!}=\\frac{1e^{-0.7}}{1}=0.497 \\text{(3 d.p.)}$\n- $P(X=1)=\\frac{0.7^1 e^{-0.7}}{1!}=\\frac{0.7e^{-0.7}}{1}=0.348 \\text{(3 d.p.)}$\n- $P(X=2)=\\frac{0.7^2 e^{-0.7}}{2!}=\\frac{0.49e^{-0.7}}{2\\times1}=0.122 \\text{(3 d.p.)}$\n- $P(X=3)=\\frac{0.7^3 e^{-0.7}}{3!}=\\frac{0.343e^{-0.7}}{3\\times2\\times1}=0.028 \\text{(3 d.p.)}$\n- $P(X=4)=\\frac{0.7^4 e^{-0.7}}{4!}=\\frac{0.2401e^{-0.7}}{4\\times3\\times2\\times1}=0.005 \\text{(3 d.p.)}$\n\n\n\n\n# Example with kick deaths\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0, 1, 2, 3, 4) \np <- c(0.497, 0.348, 0.122, 0.028, 0.005) \nplot(x, p, type = \"h\")\n```\n\n::: {.cell-output-display}\n![](lecture-03_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\n# Example with kick deaths\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrequency_kick1 <- kick %>%\n  select(-Year) %>%\n  pivot_longer(cols = everything(), names_to = \"Column\", values_to = \"Deaths\") %>%\n  count(Deaths) %>%\n  arrange(Deaths) %>%\n  mutate(Total_Deaths = Deaths*n) %>%\n  mutate(Probability = c(0.497, 0.348, 0.122, 0.028, 0.005)) %>%\n  mutate(Observed_Probability = n/280)\n\nkable(frequency_kick1)\n```\n\n::: {.cell-output-display}\n\n\n| Deaths|   n| Total_Deaths| Probability| Observed_Probability|\n|------:|---:|------------:|-----------:|--------------------:|\n|      0| 144|            0|       0.497|            0.5142857|\n|      1|  91|           91|       0.348|            0.3250000|\n|      2|  32|           64|       0.122|            0.1142857|\n|      3|  11|           33|       0.028|            0.0392857|\n|      4|   2|            8|       0.005|            0.0071429|\n\n\n:::\n:::\n\n\n\n\n\n\n- note that observed probability is n divided by the total number of observations (280). For example, for 0 deaths there were 144 observed out of a total of 280 observations i.e. the observed probability of 0 deaths in a cavalry corps over 20 years of observations was 0.51 or 51%\n\n\n\n\n\n# Example with kick deaths\n\n- So now you all can calculate what the probability is, as an example, the of having less than 2 deaths across all cavalry corps for the period of 1875-1894 $P(X<2)$.\n\n\n![](images/R_logo.jpg)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(1,0.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.844195\n```\n\n\n:::\n:::\n\n\n\n\n\n\n![](images/Excel_logo.jpg) - `=POISSON(1,0.7,TRUE)`\n\n\n\n\n\n\n\n\n# Example with kick deaths\n\n- Another example, is having exactly 2 deaths across all cavalry corps for the period of 1875-1894 $P(X=2)$.\n\n\n![](images/R_logo.jpg)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(2,0.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1216634\n```\n\n\n:::\n:::\n\n\n\n\n\n\n![](images/Excel_logo.jpg) - `=POISSON(2,0.7,FALSE)`\n\n\n\n\n\n\n# Interesting results with the binomial and Poisson distributions\n\n- For large $n$ and small p the Binomial distribution $X\\sim{Bin(n,p)}$ can be approximated by the Poisson distribution $Y\\sim{Po(\\lambda{=np})}$\n  - The general rule is if $n>20$ and $np<5$\n- We often say that the Poisson Distribution models rare events\n\n\n\n\n\n# Interesting results with the binomial and Poisson distributions\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parameters for the binomial distribution\nn <- 100\np <- 0.05\n\n# Calculating lambda for the Poisson approximation\nlambda <- n * p\n\n# Generate the range of values\nx <- 0:n\n\n# Data frames for plotting\ndata_binom <- data.frame(x = x, probability = dbinom(x, n, p), Distribution = \"Binomial\")\ndata_pois <- data.frame(x = x, probability = dpois(x, lambda), Distribution = \"Poisson\")\n\n# Combine data\ndata_combined <- rbind(data_binom, data_pois)\n\n# Create the plot\np <- ggplot(data_combined, aes(x = factor(x), y = probability, fill = Distribution)) +\n    geom_bar(stat = \"identity\", position = position_dodge()) +\n    ggtitle(\"Binomial vs Poisson Distribution\") +\n    xlab(\"Number of successes\") +\n    ylab(\"Probability\") +\n    scale_fill_manual(values = c(\"blue\", \"red\")) +\n    theme_minimal() +\n    scale_x_discrete(breaks = seq(0, n, by = 10))  # Display every 10th label\n```\n:::\n\n\n\n\n\n\n:::\n::: {.column width=\"50%\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(p)\n```\n\n::: {.cell-output-display}\n![](lecture-03_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n::::\n\n# Further reading\n\n- Quinn & Keough (2002) \n  - Chapter 1. Sections 1.5, p. 9-13\n- Mead et al. (2002)\n  - Chapter14. Sections 14.4-14.5, p. 339-377 \n\n\n\n\n\n\n\n\n\n# Thanks!\n\nThis presentation is based on the [SOLES Quarto reveal.js template](https://github.com/usyd-soles-edu/soles-revealjs) and is licensed under a [Creative Commons Attribution 4.0 International License][cc-by].\n\n\n<!-- Links -->\n[cc-by]: http://creativecommons.org/licenses/by/4.0/\n",
    "supporting": [
      "lecture-03_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}